baseURL: "https://bootique.io/"
languageCode: "en-us"
title: "Bootique: Minimally Opionated Framework for Runnable Java"
theme: "bootique-theme"

params:
  googleAnalytics: "UA-74603008-1"
  description: >-
      Bootique is a minimally opinionated platform for runnable Java applications.
      Provides command-line launcher, dependency injection service, configuration and lots of extension modules.
  keywords: "Bootique, Bootique project, Guice, Container-less Java, Runnable Jar, Make Jar not War, WYSIWYR"

# URLs for pages under folders content/page and content/docs.
permalinks:
  page: ":filename/"
  docs: "docs/0/:filename/"

menu:
  main:
    - Name: "Get started"
      URL: "/docs/0/getting-started/"
      Weight: 1
    - Name: "Documentation"
      URL: "/docs/"
      Weight: 2
    - Name: "CLA"
      URL: "/cla/"
      Weight: 3
    - Name: "Forum"
      URL: "https://groups.google.com/forum/#!forum/bootique-user"
      Weight: 4
