baseURL: "https://bootique.io/"
languageCode: "en-us"
title: "Bootique: Minimally Opinionated Framework for Runnable Java"
theme: "bootique-theme"

disableKinds:
  - RSS
  - taxonomy
  - term

enableRobotsTXT: true

params:
  googleAnalytics: "UA-74603008-1"
  description: >-
      Bootique is a minimally opinionated platform for runnable Java applications.
      Provides command-line launcher, dependency injection service, configuration and lots of extension modules.
  keywords: "Bootique, Bootique project, Guice, Container-less Java, Runnable Jar, Make Jar not War, WYSIWYR"
  sitemapExcludes: ["/page/", "/docs/", "/categories/", "/tags/"]

# URLs for pages under folders content/page and content/docs.
permalinks:
  page: ":filename/"

menu:
  main:
    - name: "Get started"
      pre: version # this means that item's URL depends on Bootique version
      url: "/getting-started/"
      weight: 1
    - name: "Documentation"
      pre: version
      url: "/docs/"
      weight: 2
    - name: "CLA"
      url: "/cla/"
      weight: 3
    - name: "Forum"
      url: "https://groups.google.com/forum/#!forum/bootique-user"
      weight: 4
