name: 'deploy site'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build and deploy site
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout...
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # setup environment: Hugo, JDK and Node

      - name: Setup Hugo...
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'

      - name: Set up JDK 11...
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up NodeJS 12...
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      # Build site

      - name: Yarn build app...
        run: cd ./app && yarn run build
        shell: bash

      - name: Yarn build scripts...
        run: cd ./scripts && yarn run build
        shell: bash

      - name: Run Hugo...
        run: hugo

#      - name: Deploy...
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./public
